# It is a convention to define anchors in a separate, non-standard mapping.
x-colors:
  fg0: &fg0 "#d4be98"
  fg1: &fg1 "#ddc7a1"
  red: &red "#ea6962"
  orange: &orange "#e78a4e"
  yellow: &yellow "#d8a657"
  green: &green "#a9b665"
  aqua: &aqua "#89b482"
  blue: &blue "#7daea3"
  purple: &purple "#d3869b"
  bg_red: &bg_red "#ea6962"
  bg_green: &bg_green "#a9b665"
  bg_yellow: &bg_yellow "#d8a657"

  bg_dim: &bg_dim "#141617"
  bg0: &bg0 "#1d2021"
  bg1: &bg1 "#282828"
  bg2: &bg2 "#282828"
  bg3: &bg3 "#3c3836"
  bg4: &bg4 "#3c3836"
  bg5: &bg5 "#504945"
  bg_statusline1: &bg_statusline1 "#282828"
  bg_statusline2: &bg_statusline2 "#32302f"
  bg_statusline3: &bg_statusline3 "#504945"
  bg_visual_red: &bg_visual_red "#442e2d"
  bg_visual_yellow: &bg_visual_yellow "#473c29"
  bg_visual_green: &bg_visual_green "#333e34"
  bg_visual_blue: &bg_visual_blue "#2e3b3b"
  bg_visual_purple: &bg_visual_purple "#3c333b"
  bg_diff_red: &bg_diff_red "#3c1f1e"
  bg_diff_green: &bg_diff_green "#32361a"
  bg_diff_blue: &bg_diff_blue "#0d3138"
  bg_current_word: &bg_current_word "#32302f"

  grey0: &grey0 "#7c6f64"
  grey1: &grey1 "#928374"
  grey2: &grey2 "#a89984"

gui:
  theme:
    activeBorderColor:
      - *fg1
      - bold
    inactiveBorderColor:
      - *grey1
    optionsTextColor:
      - *bg_yellow
    selectedLineBgColor:
      - *bg5
    cherryPickedCommitBgColor:
      - *bg5
    cherryPickedCommitFgColor:
      - *orange
      - bold
    unstagedChangesColor:
      - *bg_red
    defaultFgColor:
      - *fg0
    searchingActiveBorderColor:
      - *bg_red
